language: ruby
dist: bionic # use bionic as this is the default for FCE hosts

cache:
  bundler: true

services:
- mysql

before_install:
- export TZ=Europe/London
- mysql -e 'CREATE DATABASE labwhere_test;'

before_script:
- export RAILS_ENV=test
- cp config/database.yml.example config/database.yml
- cp config/secrets.yml.example config/secrets.yml
- bundle exec rails db:setup
- bundle exec rails about

script:
- bundle exec rspec
- bundle exec rubocop -c .rubocop.yml --fail-fast

before_deploy: "./compile-build"

deploy:
  provider: releases
  api_key:
    secure: Nz+1tthHMuYX1Vhdj4FWIAxPDXR+uagRgPqhtM45t8R8cWmgKBabLgkqbObfAi+wDDjUreFDuBdbSIOCxE1xnXj7Wk6qxdQ2r+ZEpyhUgC6DH/TGid3qgzYifqDygbX6Kwq2CUMKhJxqjyEJazcaIapNcAIowi0B3I+iR+cNi3Y=
  file: release.tar.gz
  on:
    repo: sanger/labwhere
    tags: true
  file_glob: true
  skip_cleanup: true

notifications:
  slack:
    secure: iKQj0jnqYe3Gf9Ky3+7wuP/5EiFo0bnUfl+7UjWbEUwxQj+eBHeb1I3ytNfH/Gre8ATLBNTUSFg5DOU+MxEJHhoFFanMa/ECgl9qh3j5NIQnztDVj2sdR7HWHvbMJerDJJ4vYa1MsnNpFTTtSkW2/05GoSAW+KIyQsy8aBECLqs=
